### ISSUE TITLE
alert on threshold

### ISSUE THREAD

**Issue by haytxy** [K0nicki/Icinga-check-service#1]
hello,

is there a possibility to set a critical alert when CPU utilization on exact service goes a) value on zero b) between 0 to 5 ?

m

**Comment by K0nicki** [comment]
Hi @haytxy,

Scenario a:
Yes, it is possible to set this alert. There was a bug with this but I fixed it - just set a cpu_warn and cpu_crit flags to 0, e.g. 
```PowerShell
.\check_service_by_name.ps1 -service Chrome -cpu_warn 0 -cpu_crit 0 -mem_warn 10 -mem_crit 20
```

Please note that if you want to monitor only the CPU then you need to set an appropriate threshold for the memory - the default parameter value is 0. You can ignore memory utilization by setting the threshold at 100 e.g.
```PowerShell 
.\check_service_by_name.ps1 -service Chrome -cpu_warn 0 -cpu_crit 0 -mem_warn 100 -mem_crit 100
```

In the case of the b scenario, at the moment it is only possible to monitor the range of values from <cpu_warn, cpu_warn) and <cpu_crit, 100>. Custom ranges are not supported
